import type { OutputData } from "@editorjs/editorjs"

export type { OutputData as BlueprintContent }

export function generateAgenticBlueprint(opts: {
  title: string
  system: string
}): OutputData {
  const { title, system } = opts

  return {
    time: Date.now(),
    blocks: [
      {
        type: "header",
        data: { text: title, level: 1 },
      },
      {
        type: "paragraph",
        data: {
          text: `Architecture blueprint for <b>${system}</b>. Draft generated by Atlas from linked requirements — review before approving work orders.`,
        },
      },
      { type: "delimiter", data: {} },
      {
        type: "header",
        data: { text: "Goals", level: 2 },
      },
      {
        type: "list",
        data: {
          style: "unordered",
          items: [
            "Define clear boundaries and ownership for this change",
            "Document data flow, failure modes, and rollback path",
            "Identify components and agents required for implementation",
          ],
        },
      },
      {
        type: "header",
        data: { text: "Architecture", level: 2 },
      },
      {
        type: "paragraph",
        data: {
          text: "Describe services, interfaces, and dependencies. Include sequence diagrams or API contracts where relevant.",
        },
      },
      {
        type: "code",
        data: {
          code: `# Example contract\nPOST /v1/${system.replace(/-/g, "_")}\nAuthorization: Bearer <token>\nContent-Type: application/json`,
        },
      },
      {
        type: "header",
        data: { text: "Rollout plan", level: 2 },
      },
      {
        type: "checklist",
        data: {
          items: [
            { text: "Feature flag behind tenant allowlist", checked: false },
            { text: "Migration script with dry-run in staging", checked: false },
            { text: "Observability dashboards + alerts wired", checked: false },
            { text: "Rollback runbook linked in playbooks", checked: false },
          ],
        },
      },
      {
        type: "warning",
        data: {
          title: "Needs human sign-off",
          message:
            "High-risk blueprints require two-agent review and an explicit rollback plan before work orders are spawned.",
        },
      },
    ],
  }
}

export const emptyBlueprint: OutputData = {
  time: Date.now(),
  blocks: [
    {
      type: "header",
      data: { text: "Untitled blueprint", level: 1 },
    },
    {
      type: "paragraph",
      data: {
        text: "Describe the change — goals, architecture, rollout, and risks for your team.",
      },
    },
  ],
}
