import type { StudioTemplate } from "@/lib/blueprints/studio-templates.types"

function s(
  heading: string,
  body: string,
  placeholder: string
): StudioTemplate["sections"][number] {
  return { heading, body, placeholder }
}

export const STUDIO_TEMPLATE_CATALOG: StudioTemplate[] = [
  {
    id: "client-sow",
    title: "Client SOW",
    documentTitle: "Statement of Work",
    documentIntro: "Fill each section below. Use chat to draft from an attached brief.",
    description: "Phased scope, deliverables, tasks, and assumptions for client sign-off.",
    category: "client",
    deliverable: "sow",
    allowRepo: false,
    starterPrompt: "Fill in the open SOW sections from the attached brief.",
    attachmentPrompt:
      "Analyze the attached brief and fill the statement of work sections with phases, deliverables, assumptions, open questions, and numbered implementation tasks.",
    sections: [
      s("Overview", "Summarize the client goal and current vs desired state.", "Describe the project goal and what changes for the client."),
      s("In scope", "Bullet concrete deliverables the client is buying.", "• \n• \n• "),
      s("Out of scope", "Explicit exclusions to prevent scope creep.", "• \n• "),
      s("Deliverables", "Named outputs per phase with acceptance hints.", "• Phase 1: \n• Phase 2: "),
      s("Assumptions", "What must be true for the plan to hold.", "• \n• "),
      s("Open questions", "Decisions the client must make before build.", "• \n• "),
      s("Implementation tasks", "Numbered tasks with dependency and definition of done.", "1. \n2. \n3. "),
      s("Gaps to resolve", "Missing info from the source material.", "• \n• "),
    ],
  },
  {
    id: "client-proposal",
    title: "Client Proposal",
    documentTitle: "Client Proposal",
    documentIntro: "Pre-SOW proposal. Edit directly or ask chat to draft from a brief.",
    description: "Problem, approach, and phased outline before a signed SOW.",
    category: "client",
    deliverable: "sow",
    allowRepo: false,
    starterPrompt: "Fill in the proposal sections from the attached material.",
    attachmentPrompt:
      "From the attached material, fill the proposal with problem summary, approach, recommendation, phased outline, and open questions.",
    sections: [
      s("Executive summary", "One short paragraph on the opportunity.", "Summarize the opportunity in 2–3 sentences."),
      s("Problem", "What is broken or missing today.", "What pain or gap is the client facing?"),
      s("Recommended approach", "How we would solve it and why.", "Describe the recommended solution and why it fits."),
      s("Phased outline", "High-level phases without full task detail yet.", "• Phase 1: \n• Phase 2: \n• Phase 3: "),
      s("Assumptions", "Dependencies on client inputs or systems.", "• \n• "),
      s("Open questions", "What to confirm before a formal SOW.", "• \n• "),
    ],
  },
  {
    id: "client-discovery",
    title: "Discovery Brief",
    documentTitle: "Discovery Brief",
    documentIntro: "Capture what you learned on the sales or discovery call.",
    description: "Current state, pain points, systems, and success criteria before scoping.",
    category: "client",
    deliverable: "sow",
    allowRepo: false,
    starterPrompt: "Fill the discovery brief from our notes or attached call summary.",
    attachmentPrompt:
      "From the attached notes, fill the discovery brief with current state, pain points, systems, constraints, and success criteria.",
    sections: [
      s("Client context", "Who they are and what triggered this project.", "Company, team, and why now."),
      s("Current state", "How they work today.", "Describe the existing process or system."),
      s("Pain points", "What is broken, slow, or risky.", "• \n• \n• "),
      s("Systems and data", "Tools, integrations, and data sources involved.", "• \n• "),
      s("Success criteria", "How the client will judge success.", "• \n• "),
      s("Risks and constraints", "Budget, timeline, compliance, or political constraints.", "• \n• "),
    ],
  },
  {
    id: "client-handoff",
    title: "Client Handoff",
    documentTitle: "Client Handoff",
    documentIntro: "Delivery pack for the client when work moves to them or to support.",
    description: "What was delivered, how to run it, access, and open items.",
    category: "client",
    deliverable: null,
    allowRepo: false,
    starterPrompt: "Fill the handoff document for this delivery.",
    attachmentPrompt:
      "From the attached delivery notes, fill the handoff with deliverables, run instructions, access, support window, and open items.",
    sections: [
      s("Deliverables summary", "What the client received.", "• \n• "),
      s("How to use it", "Steps to operate the solution.", "1. \n2. \n3. "),
      s("Access and credentials", "Who has access and how to request changes.", "• \n• "),
      s("Support window", "Hypercare period and escalation path.", "Support dates, contacts, and SLAs."),
      s("Open items", "Known gaps or follow-up work.", "• \n• "),
    ],
  },
  {
    id: "internal-prd",
    title: "PRD",
    documentTitle: "Product Requirements",
    documentIntro: "Internal requirements doc. Edit sections or ask chat to expand from a brief.",
    description: "Goals, users, requirements, and acceptance criteria for the build team.",
    category: "internal",
    deliverable: "prd",
    allowRepo: false,
    starterPrompt: "Fill the PRD sections from the attached requirements.",
    attachmentPrompt:
      "From the attached material, fill the PRD with problem, goals, users, requirements, success metrics, and out of scope.",
    sections: [
      s("Problem", "What user or business pain this solves.", "Describe the problem clearly."),
      s("Goals", "Measurable outcomes.", "• \n• "),
      s("Users", "Primary personas and jobs to be done.", "• \n• "),
      s("Requirements", "Functional requirements with acceptance criteria.", "• \n• \n• "),
      s("Success metrics", "How we know it worked.", "• \n• "),
      s("Out of scope", "Explicit non-goals.", "• \n• "),
    ],
  },
  {
    id: "internal-tech-spec",
    title: "Technical Spec",
    documentTitle: "Technical Spec",
    documentIntro: "Buildable spec for engineering. Attach a repo from Projects if helpful.",
    description: "APIs, data, integrations, and NFRs for implementation.",
    category: "internal",
    deliverable: "spec",
    allowRepo: true,
    starterPrompt: "Fill the technical spec from the attached requirements.",
    attachmentPrompt:
      "From the attached requirements, fill the spec with context, components, APIs, data model, integrations, NFRs, and test expectations.",
    sections: [
      s("Context", "Background and constraints.", "Background, constraints, and dependencies."),
      s("Architecture overview", "Major components and responsibilities.", "• \n• "),
      s("APIs and data", "Interfaces, schemas, and ownership.", "• \n• "),
      s("Integrations", "External systems and failure handling.", "• \n• "),
      s("Non-functional requirements", "Performance, security, observability.", "• \n• "),
      s("Test expectations", "What must be verified before ship.", "• \n• "),
    ],
  },
  {
    id: "internal-arc42",
    title: "Architecture",
    documentTitle: "Architecture Blueprint",
    documentIntro: "arc42-style architecture doc. Attach a repo from Projects to ground answers in chat.",
    description: "Context, building blocks, runtime, and deployment views.",
    category: "internal",
    deliverable: "spec",
    allowRepo: true,
    starterPrompt: "Fill the architecture sections. Attach a repo for codebase-aware chat.",
    attachmentPrompt:
      "Using attached context, fill the architecture doc with context, quality goals, building blocks, runtime, and deployment views.",
    sections: [
      s("Introduction and goals", "System purpose and quality goals.", "Purpose and top quality goals."),
      s("Constraints", "Technical and organizational limits.", "• \n• "),
      s("Context and scope", "External systems and boundaries.", "• \n• "),
      s("Building blocks", "Main components and responsibilities.", "• \n• \n• "),
      s("Runtime view", "How requests and data flow.", "Describe key flows."),
      s("Deployment view", "Where it runs and how it is operated.", "Environments, hosting, and ops notes."),
    ],
  },
  {
    id: "internal-change-request",
    title: "Change Request",
    documentTitle: "Change Request",
    documentIntro: "Scope change after the original SOW. Document delta, impact, and approval.",
    description: "What changed, timeline and cost impact, and client decision.",
    category: "internal",
    deliverable: "sow",
    allowRepo: false,
    starterPrompt: "Fill this change request from the client ask or meeting notes.",
    attachmentPrompt:
      "From the attached notes, fill the change request with requested change, rationale, impact on scope, timeline, cost, and approval path.",
    sections: [
      s("Requested change", "What the client wants added or changed.", "Describe the change clearly."),
      s("Rationale", "Why they want it.", "Business reason or trigger."),
      s("Impact on scope", "What else moves or conflicts.", "• \n• "),
      s("Timeline impact", "How dates shift.", "Original vs revised dates."),
      s("Cost impact", "Additional effort or budget.", "Estimate and assumptions."),
      s("Approval", "Who signs off and by when.", "Approver, date, and next step."),
    ],
  },
]
